export const ACCESS_TOKEN = "chatToken";
export const REFRESH_TOKEN = "chatRefreshToken";
export const NEW_CHANNEL_CREATED_NOTIFICATION = "NEW_CHANNEL_NOTIFICATION";
export const NEW_MESSAGE_NOTIFICATION = "NEW_MESSAGE_NOTIFICATION";
export const CHANNEL_MESSAGE_NOTIFICATION = "CHANNEL_MESSAGE_NOTIFICATION";
